-- Find total customers by countries
SELECT  country,
		COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT  gender,
		COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by cateogry
SELECT category,
	  COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category
SELECT category,
	  AVG(cost) AS average_costs
FROM gold.dim_products
GROUP BY category
ORDER BY average_costs DESC

-- What is the total revenue generated for each category
SELECT 
	d.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products d
ON f.product_key = d.product_key
GROUP BY d.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
SELECT d.customer_key, 
	   d.first_name,
	   d.last_name,
	   SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers d
ON f.customer_key = d.customer_key
GROUP BY d.customer_key, d.first_name, d.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across country
SELECT 
	 d.country,
	 SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers d
ON f.customer_key = d.customer_key
GROUP BY d.country
ORDER BY  total_sold_items DESC
